HumanCellAtlas/dcp

Makefile
tests/test_end_to_end_dcp.py
tests/utils.py

Also added DataStoreAgent download_bundle() and download_file() for future use.

tent_end_to_end_dcp.py: retrieve results bundle manifest and check it

---

tests/integration/test_end_to_end_dcp.py

The outputs to the SmartSeq2 pipeline change will change with https://github.com/HumanCellAtlas/skylab/pull/126.
This PR updates the part of the DCP integration test that references the SS2 analysis output files but it should not be merged in until the greenbox is using the new version of the pipeline!

Update SS2 analysis output regexes

---

.gitlab-ci.yml
tests/dataset_fixture.py
tests/fixtures/datasets/10x/README.json
tests/integration/test_end_to_end_dcp.py

- Add a test for the 10x cellranger pipeline 
- Separate the gitlab job for `dcp_wide_test` into a separate job for each pipeline. Since the stage is the same for both jobs, the dcp_wide_test pipeline will run both of them in parallel:  
Fixes: https://github.com/HumanCellAtlas/secondary-analysis/issues/248
Note: The 10x test will only pass in the `integration` environment, until [this fix](https://github.com/HumanCellAtlas/pipeline-tools/pull/90) to the pipeline outputs is promoted to the `staging`environment for secondary analysis.

Add 10x pipeline to DCP-wide integration test

---

tests/dataset_runner.py
tests/integration/test_end_to_end_dcp.py

instead of always using "integration" which was weird for staging tests.
Also print out the project_shortname first thing in the run.

In integration tests use deployment as project_shortname prefix

---

tests/dataset_runner.py
tests/matrix_agent.py

This PR integrates matrix service into dcp wide test. It tests both the zarr and loom (which utilizes file conversion) output code paths.

integrate matrix service into dcp wide test

---

tests/dataset_runner.py

This PR switches dcp test to using hca cli. This is to be merged in after https://github.com/HumanCellAtlas/dcp-cli/pull/217 is merged in.

use hca cli with aws s3 source instead of using aws sync to upload files

---

.gitlab-ci.yml
tests/dataset_runner.py
tests/ingest_agents.py

Retrieving the headers every request should be fine since token manager inside hca-ingest is handling the caching and refreshing the token (every ~1hr)
https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp/-/jobs/19037

Ingest headers must always get the cached and refreshed token

---

tests/integration/test_end_to_end_dcp.py
tests/utils.py

Tested on the integration test with 6 second timeouts.

Timeout should actually wrap test logic

---

tests/integration/test_end_to_end_dcp.py

Also raise on timeout to indicate test failure.
This fixes a bug causing bundle cleanup to fail after timeouts. Note that a race condition inherent in the timeout-cleanup mechanism prevents cleanup from being 100% reliable.
We should consider setting primary and secondary bundle UUIDs from within the test. In addition to cleanup reliability, this would allow the data-store to completely delete (not just tombstone) test data in the future.

Ensure runner exists during timeout

---

RELEASE_NOTES.md
components.yml

A quick comment about the content of these release notes:  I have added them verbatim from the release notes google doc, however many of them are garbage.  The purpose of release notes is to inform users of your code what, if any, changes they may notice (e.g. new or deprecated features), or what changes they may need to make because of changes in the **external** API of the code.
Their purpose is not to record what commits were pushed, we have git history for that.  If you can edit the release notes in this PR to remove the component-internal noise, or just do that in future, that would be great.  Thanks.

Release notes: prod 2019/03/12

---

.gitlab-ci.yml
requirements.txt
tests/analysis_agent.py
tests/analysis_entities.py
tests/dataset_runner.py

I have tested this PR in both happy paths and unhappy paths:
- Unhappy path 1 No creds provided for analysis: https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp/pipelines/8561
- Unhappy path 2 Workflow got aborted in the middle of the test (similar to the workflow failed in the process): https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp/-/jobs/23520
- Happy paths: 
- the test ran through analysis and show all of the info in the console: 
https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp/-/jobs/23522
- the test2 ran through analysis and show all of the info in the console: 
https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp/-/jobs/24026

Add better logging around analysis workflows for the dcp test suite

---

.gitlab-ci.yml
tests/dataset_runner.py
tests/fixtures/datasets/optimus/README.json
tests/integration/test_end_to_end_dcp.py

This PR adds a test for the Optimus pipeline, which should be run as a part of the integration tests after the pipeline is running in the DCP.

Add Optimus to integration test

---

tests/integration/test_end_to_end_dcp.py

Fixes the issue where a failure raised in `self.ingest_store_and_analyze_dataset` due to a failed analysis workflow caused the test to fail before reaching the call to `cleanup_primary_and_result_bundles()`

Always clean up test bundles

---

tests/integration/test_end_to_end_dcp.py

Temporarily remove this until this file is submitted with the rest of the pipeline results.

Remove empty_drops_result

---

.gitlab-ci.yml
tests/analysis_agent.py
tests/dataset_runner.py
tests/integration/test_end_to_end_dcp.py

**Purpose:**
If a test times out while an analysis workflow is running and the workflow later succeeds, it will result in test analysis bundles that show up in the data browser. This is especially an issue for integration tests running in production. 
**Changes:**
- If the test times out, abort any running workflows in Cromwell and then verify that the status is "Aborted":
https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp/-/jobs/27297
**Note:** 
Any thoughts on how to abort workflows if a test is cancelled would be helpful!!

Abort running workflows if test times out

---

tests/dataset_runner.py

- Fix an issue with the analysis clean up function which breaks the whole build if workflows are already in terminated statuses.
- Add a link to the Job Manager page when a workflow failed, this is for a smoother debugging.

Fix an issue with the analysis clean up func

---

RELEASE_NOTES.md
components.yml

Updated subscription queries for SmartSeq2 and Optimus to only get notified of testing data to unblock updating existing submissions

Hotfix: Update prod subscriptions

---

RELEASE_NOTES.md
components.yml

Several Optimus workflows in production are failing due to an intermittent issue with the pipelines API. Adding maxRetries to the workflow options will tell Cromwell to retry any failed tasks automatically, which should reduce this error rate and allow us to finish analyzing the datasets.

Hotfix analysis service

---

.gitlab-prod-ci.yml
tests/cleanup/cleanup_test_bundles.py
tests/data_store_agent.py

This adds two GitLab jobs that:
1. Find test bundles in the production deployment of the DSS and output them to the job log. This will run after every DCP-wide integration test.
1. Tombstone test bundles in the production deployment of the DSS. This must be manually triggered.
For this to work, the DCP-wide integration test service account needs to be authorized to tombstone bundles in the DSS.

Add GitLab jobs to find and (manually) tombstone test bundles

---

.gitlab-prod-ci.yml

This allows test bundle identification and cleanup to proceed even if the dcp-wide integration tests fail. Failed pipelines will be [highlighted orange instead of red](https://docs.gitlab.com/ee/ci/yaml/#allow_failure).

Continue pipeline if integration tests fail.

---

.gitlab-prod-ci.yml

As discussed, lets run auto cleanup if one of the earlier stages fails. If all stages pass, there is no need to run cleanup as the stages should have cleaned up after themselves.

run cleanup on failure
