HumanCellAtlas/dcp

- tests/ingest_agents.py
- tests/test_end_to_end_dcp.py
In this PR:
1. I add an IngestAuthAgent class to interact with the new Ingest Service.
2. Include authentication headers where it's necessary for the test suite.
> Add IngestAuthAgent and include authentication headers

- Makefile
- tests/dataset_fixture.py
- tests/dataset_runner.py
- tests/ingest_agents.py
After spreadsheet is uploaded, wait for files tab to be processed before uploading files
> Wait before uploading files

- tests/dataset_runner.py
aws s3 sync sometimes doesn't set the desired content-type.
Check all files and correct content-type where necessary.
> Fix bad content types after s3 sync

- components.yml
Update `data-store` to version 4e9e1e52375a59bfcbddc72137a9694a1ffd6367.
> bluebox prod -> 4e9e1e52375a59bfcbddc72137a9694a1ffd6367

- tests/integration/test_end_to_end_dcp.py
Adapt to the new bundle structure and new metadata schema.
> Fix the Analysis output checker

- tests/azul_agent.py
- tests/dataset_runner.py
Last commit to be removed after testing.
> Assert Orange indexes analysis bundle

- tests/dataset_runner.py
e.g.
```
0:00:01     found new primary bundle: 6e39ffaa-db85-4ceb-8e39-3cb468272fec
0:00:02     found new results bundle: 0ce212d1-16a4-44d9-ae08-2c83f48fff88
```
> Print bundle UUID when new primary/results bundle is discovered

- tests/dataset_runner.py
Will remove `CI_COMMIT_REF_NAME` hacks after review.
> Add Orange to scaling tests

- tests/dataset_runner.py
Reverts HumanCellAtlas/dcp#145
> Revert "Add Orange to scaling tests"

- tests/integration/test_end_to_end_dcp.py
The analysis_protocol was not linked to analysis_process properly, we fixed that issue in Green Box, but this test also needs to be updated.
> Add checker for analysis_protocol.json.

- RELEASE_NOTES.md
Please check your release notes.
If they need changes, add a commit on this branch.
When good, approve the PR.
> Prod Release Notes for 2018/10/23

- tests/dataset_runner.py
This is a short term fix to ensure the tags exist on objects during integration test while we figure out how to switch to hca cli + handle simultaneous file uploads.
> short term fix for file object tagging in dcp test

- tests/data_store_agent.py
* This makes it more straighfoward to pull in credentials for authed endpoints, and
* it seems reasonable to exercise the CLI during tests
> Use dcp-cli python bindings to access data-store

- .gitlab-ci.yml
This credentials the DSS agent to tombstone test bundles
> Grab DSS credentials from AWS secretsmanager

- tests/dataset_runner.py
- tests/integration/test_end_to_end_dcp.py
The tests expect bundle availability after runner.run()
> Move DSS cleanup from runner to dcp-wide tests

- README.md
- SECURITY.md
- security.txt
See conversation here: https://github.com/HumanCellAtlas/dcp/issues/274
Other projects would link to this `SECURITY.md` file.
> Update security.txt to a detailed SECURITY.md.

- .gitlab-ci.yml
- tests/dataset_runner.py
- tests/fixtures/datasets/optimus/README.json
- tests/integration/test_end_to_end_dcp.py
* Add optimus to integration test
* Disable cellranger test
* Commit for testing
* Change test spreadsheet
* Update testing spreadsheet
* Adjust timeout for optimus test
* Update timeout for optimus test
* Include matrix service in optimus test
* Disable matrix service in integration tests
* Remove unused cellranger test
* Remove commit for testing
> Add Optimus to integration test (#333)

- tests/dataset_runner.py
- tests/integration/test_end_to_end_dcp.py
- Fix an issue with the analysis clean up function
- Increase Optimus test timeout
> Update prod test

- .gitlab-ci.yml
- .gitlab-prod-ci.yml
Temporarily disable the Optimus test in **PROD**, until we fix the Optimus pipeline.
This is to unblock the re-ingestion effort in PROD.
> Temporarily disable the Optimus test.

- RELEASE_NOTES.md
- components.yml
Update to version optimus_v1.3.2, which increases the memory allocated to the RunEmptyDrops task
> Update optimus pipeline version

- .gitlab-ci.yml
- tests/dataset_runner.py
- tests/ingest_agents.py
- tests/integration/test_end_to_end_dcp.py
- tests/wait_for.py
This PR is to address the issue with the original PR(#454) branch being branched off of `integration` instead of `master`. Please check the link to the original for some additional context.
> Defined end-to-end test for metadata bundle update

- README.md
- tests/dataset_runner.py
- tests/ingest_agents.py
Updated instructions and flag to allow for retention of bundles for testing purposes
> update local instructions

- .gitlab-prod-ci.yml
See slack thread starting at https://humancellatlas.slack.com/archives/G9XD6L0AD/p1566234049347600
This reverts commit 32808a67645fe3629dd97d24d5b1c5cc4057555c.
> Revert "Continue pipeline if integration tests fail. (#470)"

- .gitlab-prod-ci.yml
- tests/cloudwatch_handler.py
- tests/integration/test_end_to_end_dcp.py
Log invocation and failures of dcp tests for reliability measurement
> log invocation and failures to cloudwatch metrics

- tests/dataset_runner.py
- tests/matrix_agent.py
Merge after [MS resubscribes to DSS notifications](https://github.com/HumanCellAtlas/matrix-service/pull/394)
> Re-enable matrix service in integration tests

- tests/dataset_runner.py
- Fix a false positive which fails the test.
> Fix a false positive.

- .gitlab-ci.yml
- .gitlab-prod-ci.yml
adds date/time for execution in CI output for easier referencing.
> DCP CI: date output
